frontend:
  - 'frontend/**/*'
  - '**/frontend/**/*'

backend:
  - 'backend/**/*'
  - '**/backend/**/*'

documentation:
  - 'docs/**/*'
  - '**.md'
  - 'LICENSE'

tests:
  - '**/tests/**/*'
  - '**/test_*'
  - '**/*_test.*'
  - '**/*.spec.*'

ci:
  - '.github/**/*'
